### ISSUE TITLE
Spotted on Matt Stauffer's livestream

### ISSUE THREAD

**Issue by DCzajkowski** [matthijs110/matthijs110.github.io#2]
Hi man :)
I didn't know how to contact you other than here :P So here I am :)

You got spotted! 😄 
![](http://i.imgur.com/9WeOFPC.png)

_Close the issue when you see it :P_

**Comment by matthijs110** [comment]
Darn.. You found my o;

**Comment by DCzajkowski** [comment]
haha. How is it going?

**Comment by matthijs110** [comment]
I'm fine. I found some free time to code again 😃. What about you?

**Comment by DCzajkowski** [comment]
Not bad. Uni now. That sucks. But the next year I am having IT only and no more Maths nor Physics. So that's good. :)
Also coding a little, but probably gonna get a job in the industry (remote Laravel, so the best from the best 😆 )

**Comment by DCzajkowski** [comment]
Also fully finished my new website design and it's live for two weeks or so :)

**Comment by matthijs110** [comment]
Nice to hear! Your website looks great! Ready for christmas 😃

**Comment by DCzajkowski** [comment]
Thank you <3 Nice to hear that. If there was anything you think should change, drop me a message or open the issue on GH (I will add you to the repo, if you want :) ).

Cheers :)
